[book]
authors = ["Stephan Kunz"]
description = "A comprehensive guide to DiMAS"
language = "en"
multilingual = false
src = "src"
title = "Programming distributed Agents"

[rust]
edition = "2021"

[output.html]
site-url = "/book/"
